use std::collections::BTreeSet;

use serde_json::Value;

use crate::fixtures::{
    ExpectedManifestEntry, FixtureCasesFile, FixtureError, PROFILE_1_KISS_RNODE,
    assert_exact_manifest_entries, parse_fixture_cases_for_profile, parse_manifest_for_profile,
};
use crate::report::{ConformanceEnvironment, ConformanceResult, ConformanceRun};
use crate::runner::{fixture_result, invalid_environment_result};

pub const CATEGORY_FIXTURE_MANIFEST: &str = "fixture_manifest";
pub const CATEGORY_KISS: &str = "kiss";
pub const CATEGORY_RNODE_COMMAND: &str = "rnode_command";
pub const CATEGORY_RNODE_CONFIG_VALIDATION: &str = "rnode_config_validation";
pub const CATEGORY_RNODE_STAT: &str = "rnode_stat";
pub const CATEGORY_RNS_ORACLE_FIXTURE_REPLAY: &str = "rns_oracle_fixture_replay";

pub const RESULT_ID_FIXTURE_MANIFEST: &str = "profile_1_kiss_rnode.fixture_manifest";
pub const RESULT_ID_KISS: &str = "profile_1_kiss_rnode.kiss";
pub const RESULT_ID_RNODE_COMMAND: &str = "profile_1_kiss_rnode.rnode_command";
pub const RESULT_ID_RNODE_CONFIG_VALIDATION: &str = "profile_1_kiss_rnode.rnode_config_validation";
pub const RESULT_ID_RNODE_STAT: &str = "profile_1_kiss_rnode.rnode_stat";
pub const RESULT_ID_RNS_ORACLE_FIXTURE_REPLAY: &str =
    "profile_1_kiss_rnode.rns_oracle.fixture_replay";

pub const REQUIRED_PROFILE_1_RESULTS: &[(&str, &str)] = &[
    (RESULT_ID_FIXTURE_MANIFEST, CATEGORY_FIXTURE_MANIFEST),
    (RESULT_ID_KISS, CATEGORY_KISS),
    (RESULT_ID_RNODE_COMMAND, CATEGORY_RNODE_COMMAND),
    (
        RESULT_ID_RNODE_CONFIG_VALIDATION,
        CATEGORY_RNODE_CONFIG_VALIDATION,
    ),
    (RESULT_ID_RNODE_STAT, CATEGORY_RNODE_STAT),
    (
        RESULT_ID_RNS_ORACLE_FIXTURE_REPLAY,
        CATEGORY_RNS_ORACLE_FIXTURE_REPLAY,
    ),
];

pub const REQUIRED_PROFILE_1_RESULT_CATEGORIES: &[&str] = &[
    CATEGORY_FIXTURE_MANIFEST,
    CATEGORY_KISS,
    CATEGORY_RNODE_COMMAND,
    CATEGORY_RNODE_CONFIG_VALIDATION,
    CATEGORY_RNODE_STAT,
    CATEGORY_RNS_ORACLE_FIXTURE_REPLAY,
];

const MANIFEST: &str = include_str!("../../../fixtures/rns/profile_1_kiss_rnode/manifest.json");
const KISS_FIXTURE: &str =
    include_str!("../../../fixtures/rns/profile_1_kiss_rnode/kiss_vectors.json");
const KISS_NEGATIVE_FIXTURE: &str =
    include_str!("../../../fixtures/rns/profile_1_kiss_rnode/kiss_negative_vectors.json");
const RNODE_COMMAND_FIXTURE: &str =
    include_str!("../../../fixtures/rns/profile_1_kiss_rnode/rnode_command_vectors.json");
const RNODE_CONFIG_FIXTURE: &str =
    include_str!("../../../fixtures/rns/profile_1_kiss_rnode/rnode_config_validation_vectors.json");
const RNODE_STAT_FIXTURE: &str =
    include_str!("../../../fixtures/rns/profile_1_kiss_rnode/rnode_stat_vectors.json");

pub fn profile_1_results() -> Vec<ConformanceResult> {
    let mut results = profile_1_fixture_results();
    results.extend(profile_1_oracle_unavailable_results());
    results
}

pub fn profile_1_fixture_results() -> Vec<ConformanceResult> {
    vec![
        fixture_result(
            RESULT_ID_FIXTURE_MANIFEST,
            CATEGORY_FIXTURE_MANIFEST,
            validate_fixture_manifest(),
        ),
        fixture_result(RESULT_ID_KISS, CATEGORY_KISS, validate_kiss_fixtures()),
        fixture_result(
            RESULT_ID_RNODE_COMMAND,
            CATEGORY_RNODE_COMMAND,
            validate_fixture_cases(RNODE_COMMAND_FIXTURE, 10),
        ),
        fixture_result(
            RESULT_ID_RNODE_CONFIG_VALIDATION,
            CATEGORY_RNODE_CONFIG_VALIDATION,
            validate_fixture_cases(RNODE_CONFIG_FIXTURE, 7),
        ),
        fixture_result(
            RESULT_ID_RNODE_STAT,
            CATEGORY_RNODE_STAT,
            validate_fixture_cases(RNODE_STAT_FIXTURE, 11),
        ),
    ]
}

pub fn profile_1_oracle_unavailable_results() -> [ConformanceResult; 1] {
    [invalid_environment_result(
        RESULT_ID_RNS_ORACLE_FIXTURE_REPLAY,
        CATEGORY_RNS_ORACLE_FIXTURE_REPLAY,
        "fixture replay captures are generated by private evidence tooling",
    )]
}

pub fn profile_1_report(
    run_id: impl Into<String>,
    hyf_commit: impl Into<String>,
    started_at: impl Into<String>,
    environment: ConformanceEnvironment,
) -> ConformanceRun {
    ConformanceRun::new_profile(
        PROFILE_1_KISS_RNODE,
        run_id,
        hyf_commit,
        crate::fixtures::EXPECTED_RETICULUM_COMMIT,
        started_at,
        environment,
        profile_1_results(),
    )
}

pub fn required_categories_are_present(results: &[ConformanceResult]) -> bool {
    let categories: BTreeSet<&str> = results
        .iter()
        .map(|result| result.category.as_str())
        .collect();
    REQUIRED_PROFILE_1_RESULT_CATEGORIES
        .iter()
        .all(|category| categories.contains(category))
}

fn validate_fixture_manifest() -> Result<(), FixtureError> {
    let manifest = parse_manifest_for_profile(MANIFEST, PROFILE_1_KISS_RNODE)?;

    assert_exact_manifest_entries(
        &manifest,
        &[
            ExpectedManifestEntry {
                file: "kiss_vectors.json",
                category: CATEGORY_KISS,
                case_count: 5,
                contents: KISS_FIXTURE,
            },
            ExpectedManifestEntry {
                file: "kiss_negative_vectors.json",
                category: "kiss_negative",
                case_count: 4,
                contents: KISS_NEGATIVE_FIXTURE,
            },
            ExpectedManifestEntry {
                file: "rnode_command_vectors.json",
                category: CATEGORY_RNODE_COMMAND,
                case_count: 10,
                contents: RNODE_COMMAND_FIXTURE,
            },
            ExpectedManifestEntry {
                file: "rnode_config_validation_vectors.json",
                category: CATEGORY_RNODE_CONFIG_VALIDATION,
                case_count: 7,
                contents: RNODE_CONFIG_FIXTURE,
            },
            ExpectedManifestEntry {
                file: "rnode_stat_vectors.json",
                category: CATEGORY_RNODE_STAT,
                case_count: 11,
                contents: RNODE_STAT_FIXTURE,
            },
        ],
    )
}

fn validate_kiss_fixtures() -> Result<(), FixtureError> {
    validate_fixture_cases(KISS_FIXTURE, 5)?;
    validate_fixture_cases(KISS_NEGATIVE_FIXTURE, 4)
}

fn validate_fixture_cases(contents: &str, expected_count: usize) -> Result<(), FixtureError> {
    let fixture: FixtureCasesFile<Value> =
        parse_fixture_cases_for_profile(contents, PROFILE_1_KISS_RNODE)?;
    if fixture.cases.len() == expected_count {
        return Ok(());
    }

    Err(FixtureError::UnexpectedFixtureValue {
        field: "case_count".to_owned(),
        value: fixture.cases.len().to_string(),
    })
}
